# Use the official Go image as the base
FROM golang:1.24.0 as builder

# Set the working directory
WORKDIR /korotole.com

# Copy and download dependencies
COPY src/go.mod src/go.sum ./
RUN go mod download

# Copy the rest of the application code
COPY src .

# Build the application
RUN go build -o bin-website main.go

# Use a minimal image for the final container
FROM debian:bookworm-slim

# Set the working directory for container
WORKDIR /korotole.com/website

# Copy static files
COPY static /korotole.com/website/static
COPY files /korotole.com/website/files

# Copy built binary from the builder
COPY --from=builder /korotole.com/bin-website /korotole.com/bin-website

# Expose the application's port
EXPOSE 8080

# Run the web service
CMD ["/korotole.com/bin-website"]
